version: "3.8"

networks:
  callhome-base-net:
    driver: bridge

volumes:
  callhome-timescaledb-data:

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: callhome-timescaledb
    restart: on-failure
    env_file:
      - .env
    volumes:
      - callhome-timescaledb-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${MF_CALLHOME_TIMESCALE_PASSWORD}
      POSTGRES_USER: ${MF_CALLHOME_TIMESCALE_USER}
      POSTGRES_DB: ${MF_CALLHOME_TIMESCALE_DB_NAME}
    networks:
      - callhome-base-net
  callhome-server:
    image: magistrala/callhome:${MG_CALLHOME_RELEASE_TAG}
    container_name: callhome-server
    depends_on:
      - timescaledb
    restart: on-failure
    env_file:
      - .env
    networks:
      - callhome-base-net
    volumes:
      - ./IP2LOCATION-LITE-DB5.IPV6.BIN:/IP2LOCATION-LITE-DB5.IPV6.BIN
  certbot:
    image: certbot/certbot
    volumes:
     - ./certbot/conf:/etc/letsencrypt
     - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  nginx:
    image: nginx
    container_name: callhome-nginx
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - "callhome-server"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - callhome-base-net
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
  jaeger:
    image: jaegertracing/all-in-one:1.46.0
    container_name: magistrala-jaeger
    ports:
      - ${MF_JAEGER_PORT}:${MF_JAEGER_PORT}/udp
      - ${MF_JAEGER_FRONTEND}:${MF_JAEGER_FRONTEND}
      - ${MF_JAEGER_COLLECTOR}:${MF_JAEGER_COLLECTOR}
      - ${MF_JAEGER_CONFIGS}:${MF_JAEGER_CONFIGS}
    networks:
      - callhome-base-net
