version: "3.8"

networks:
  et-base-net:
    driver: bridge

volumes:
  timescaledb-data:

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: callhome-timescaledb
    restart: on-failure
    env_file:
      - .env
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${MF_CALLHOME_TIMESCALE_PASSWORD}
      POSTGRES_USER: ${MF_CALLHOME_TIMESCALE_USER}
      POSTGRES_DB: ${MF_CALLHOME_TIMESCALE_DB_NAME}
    networks:
      - et-base-net
  callhome-server:
    image: mainflux/callhome:${MF_CALLHOME_RELEASE_TAG}
    container_name: callhome-server
    depends_on:
      - timescaledb
    restart: on-failure
    env_file:
      - .env
    ports:
      - ${MF_CALLHOME_PORT}:${MF_CALLHOME_PORT}
    networks:
      - et-base-net
    volumes:
      - ./creds.json:/creds.json
      - ./IP2LOCATION-LITE-DB5.BIN:/IP2LOCATION-LITE-DB5.BIN
